"""
Copyright (c) 2017 Doyub Kim

I am making my contributions/submissions to this project solely in my personal
capacity and am not conveying any rights to any intellectual property of any
third parties.
"""

Import('env', 'os', 'utils')

script_dir = os.path.dirname(File('SConscript').rfile().abspath)

app_env = env.Clone()

source = ['main.cpp']

app = app_env.Program('hello_fluid_sim', source)

Return('app_env', 'app')
