"""
Copyright (c) 2016 Doyub Kim
"""

Import('env', 'os', 'utils')

script_dir = os.path.dirname(File('SConscript').rfile().abspath)

lib_env = env.Clone()
lib_env.Append(CPPPATH = [
    os.path.join(script_dir, '../../include'),
    os.path.join(script_dir, '../../external/include'),
    os.path.join(script_dir, '../../external/src/obj'),
    script_dir])

source_patterns = ['*.cpp']
source = map(lambda x: os.path.relpath(x, script_dir), utils.get_all_files(script_dir, source_patterns))
source = [s for s in source if not (s.startswith('dx') or s.startswith('win32') or s.endswith('pch.cpp'))]

lib = lib_env.Library('jet', source)

Return('lib_env', 'lib')

