FROM ubuntu:16.04
MAINTAINER Doyub Kim <doyubkim@gmail.com>

RUN apt-get update -yq && \
    apt-get install -yq build-essential python-dev python-pip cmake

ADD . /app

WORKDIR /app/build
RUN cmake .. -DUSE_GL=OFF && \
    make && \
    make install && \
    bin/unit_tests

RUN apt-get install -yq pkg-config libfreetype6-dev libpng-dev
RUN pip install -r ../requirements.txt && pip install ..

WORKDIR /
